services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: posts_app
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: postsdb
      DB_PORT: 5432
      STORAGE_TYPE: POSTGRES
    ports:
      - "8080:8080"

volumes:
  postgres_data:
