// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string              `json:"id"`
	PostID   int32               `json:"postId"`
	ParentID *int32              `json:"parentId,omitempty"`
	Body     string              `json:"body"`
	Author   string              `json:"author"`
	Replies  *CommentsConnection `json:"replies"`
}

type CommentsConnection struct {
	Edges    []*CommentsEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type CommentsEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	Body     string `json:"body"`
	Author   string `json:"author"`
	PostID   int32  `json:"postId"`
	ParentID *int32 `json:"parentId,omitempty"`
}

type NewPost struct {
	Title         string `json:"title"`
	Body          string `json:"body"`
	Author        string `json:"author"`
	AllowComments bool   `json:"allowComments"`
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}

type Post struct {
	ID            string              `json:"id"`
	Title         string              `json:"title"`
	Body          string              `json:"body"`
	AllowComments bool                `json:"allowComments"`
	Author        string              `json:"author"`
	Comments      *CommentsConnection `json:"comments"`
}

type Query struct {
}
